# Generated by Django 4.1 on 2023-03-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='awayTeam',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='entries',
            old_name='homeTeam',
            new_name='home_team',
        ),
        migrations.RenameField(
            model_name='entries',
            old_name='option',
            new_name='selected_option',
        ),
        migrations.AddField(
            model_name='entries',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
