# Generated by Django 4.1 on 2023-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFL', '0003_alter_entries_table_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
