# Generated by Django 4.1 on 2023-03-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFL', '0007_rename_fixture_id_results_fixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixtures',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='fixtures',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fixtures',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='results',
            name='fixture',
        ),
    ]
