# Generated by Django 4.1 on 2023-03-01 17:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NFL', '0009_alter_fixtures_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='away_team',
            field=models.CharField(default='xxx', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixtures',
            name='competition',
            field=models.CharField(default='xxx', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixtures',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 17, 46, 59, 466435, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixtures',
            name='division',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixtures',
            name='home_team',
            field=models.CharField(default='xxx', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixtures',
            name='time',
            field=models.CharField(default='xx', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='away_goals',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='away_points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='fixture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NFL.fixtures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='home_goals',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='home_points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='result',
            field=models.CharField(default='Draw', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='results',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
