# Generated by Django 4.1 on 2023-03-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFL', '0010_fixtures_away_team_fixtures_competition_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entries',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fixtures',
            table=None,
        ),
        migrations.AlterModelTable(
            name='results',
            table=None,
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
