# Generated by Django 4.1 on 2023-03-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFL', '0014_users_current_score_users_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
