# Generated by Django 4.1 on 2023-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFL', '0015_entries_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='current_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
