# Generated by Django 4.1 on 2024-01-18 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NFL', '0018_delete_entries_remove_results_fixture_delete_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('division', models.IntegerField()),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('selection', models.CharField(max_length=255)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NFL.fixture')),
            ],
        ),
    ]
