# Generated by Django 4.1 on 2024-01-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFL', '0020_rename_round_fixture_league_round_fixture_deadline_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixture',
            unique_together={('home_team', 'away_team', 'year', 'league_round')},
        ),
    ]
