# Generated by Django 4.1 on 2024-01-22 20:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NFL', '0021_alter_fixture_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='form_uuid',
            field=models.UUIDField(default=uuid.UUID('b2cfa970-1184-4b69-9a15-f4a690371e21')),
        ),
    ]
