# Generated by Django 4.1 on 2024-01-25 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NFL', '0022_response_form_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='form_uuid',
            field=models.UUIDField(default=uuid.UUID('2f5536d2-0343-45df-8149-76b8836c940e')),
        ),
    ]
